apiVersion: v1
kind: Pod
metadata:
  name: bert-run
spec:
  restartPolicy: Never
  # Force the Pod to run on the same Node where the PVC was bound
  nodeSelector:
    kubernetes.io/hostname: sno
  containers:
  - name: bert
    image: quay.io/meyceoz/bert_tf2
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /workspace/bert_tf2/
      name: storage-volume
    - mountPath: /dev/shm
      name: dshm
    command:
    - bash
    - -c
    - "bash scripts/run_squad.sh 1 12 5e-6 fp16 true large 1.1 2"
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: benchmarking-bert-dataset
  - name: dshm
    emptyDir:
      medium: Memory
