apiVersion: v1
kind: Pod
metadata:
 name: coco-dataset-downloader
spec:
  restartPolicy: Never
  nodeSelector:
    # Force the Pod to run on a given Node
    kubernetes.io/hostname: sno
  containers:
  - name: coco-dataset-downloader
    image: registry.access.redhat.com/ubi8/ubi
    command: [bash, /mnt/entrypoint/entrypoint.sh]
    env:
    - name: CRED_FILE
      value: /etc/s3-secret/cococred.csv
    - name: STORAGE_DIR
      value: /storage
    volumeMounts:
    - name: s3-secret
      mountPath: /etc/s3-secret
      readOnly: true
    - name: entrypoint-cm
      mountPath: /mnt/entrypoint/entrypoint.sh
      readOnly: true
      subPath: entrypoint.sh
    - name: storage
      mountPath: /storage/
  volumes:
  - name: s3-secret
    secret:
      secretName: s3-secret
  - name: storage
    persistentVolumeClaim:
      claimName: benchmarking-coco-dataset1
  - name: entrypoint-cm
    configMap:
      defaultMode: 0777
      name: coco-dataset-downloader
